/*
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements. See the NOTICE file
distributed with this work for additional information
regarding copyright ownership. The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License. You may obtain a copy of the License at
  http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied. See the License for the
specific language governing permissions and limitations
under the License.
*/

#include <onika/log.h>
#include <onika/scg/operator.h>
#include <onika/scg/operator_slot.h>
#include <onika/scg/operator_factory.h>
#include <onika/math/basic_types.h>

#include <exaStamp/delaunay/interface_mesh.h>
#include <exaStamp/delaunay/dxa_edge_vectors.h>

#include <deque>
#include <unordered_map>
#include <vector>

// DXA pipeline steps (vi)-(vii), take 2: Burgers circuit detection restricted to the interface
// mesh's own edge graph, per OVITO's documented algorithm (dislocation_analysis.rst, "Technical
// background"): "Trial circuits generated by the DXA on the interface mesh are closed sequences
// of tessellation edges, and their Burgers vectors are computed... by summing the respective
// ideal lattice vectors" -- and "The algorithm enumerates all possible circuits on the interface
// mesh in order of increasing length until one with a non-zero Burgers vector is encountered."
//
// compute_dxa_burgers_circuits.cpp already implements the right *mechanism* for this -- a spanning
// tree over resolved edges plus, for every non-tree edge, comparing its own direct ideal vector
// against the tree's accumulated position (this IS the "fundamental cycle" of that edge: the
// unique tree path between its endpoints, closed by the edge itself, is exactly a trial circuit,
// and a spanning tree naturally enumerates the full basis of independent circuits without any
// combinatorial search) -- but it runs over the WHOLE crystal's resolved-edge graph, not
// specifically the interface mesh's own edges. That matters: a global spanning tree can route an
// arbitrarily long path through slightly-strained bulk before reaching a given edge, picking up
// small residual unrelated to the local defect the edge is actually part of, and it uses a mesh
// that's ~2.5x coarser than OVITO's own reference on the real test case (5164 vs 1648 triangles,
// see src/delaunay/README.md) -- rather than the interface mesh a Burgers circuit is actually
// supposed to be built on.
//
// This operator does the exact same spanning-tree/residual mechanism, but restricted to the
// atomistic interface mesh's own vertex/edge graph (InterfaceMesh::edge_ideal_vector, populated by
// compute_atomistic_interface_mesh from each edge's *generating crystalline atom's* own resolved
// template slots -- mesh edges connect two non-crystalline atoms, which have no orientation/ideal
// vector of their own, see that struct field's own comment). Reuses DXABurgersCircuits as the
// output (same shape: confirmed signal edges + their Burgers vector), since the concept is
// identical, just computed over a different, smaller graph.
//
// ponytail: this finds confirmed signal EDGES (a necessary first step and a directly useful
// signal on its own), not yet the actual seed-circuit-then-sweep line tracing OVITO's algorithm
// does next (advancing the circuit along the mesh, taking its center of mass at each step) -- that
// is a separate, not-yet-implemented stage (see src/delaunay/README.md).
namespace exaStamp
{
  using namespace exanb;

  class ComputeDXAMeshBurgersCircuits : public OperatorNode
  {
    ADD_SLOT( InterfaceMesh      , interface_mesh       , INPUT , REQUIRED );
    ADD_SLOT( DXABurgersCircuits , dxa_mesh_burgers_circuits , OUTPUT );
    ADD_SLOT( double             , min_burgers_norm     , INPUT , 0.5 , DocString{"Minimum Burgers circuit closure-failure magnitude (same units as InterfaceMesh::edge_ideal_vector) to count as a genuine dislocation signal rather than numerical/classification noise."} );
    ADD_SLOT( long               , n_mesh_core_edges    , OUTPUT , DocString{"Number of confirmed dislocation signal edges found on the interface mesh"} );

  public:
    inline void execute () override final
    {
      const InterfaceMesh& mesh = *interface_mesh;

      // mesh vertex/edge adjacency, restricted to edges that actually have a resolved ideal vector
      // (hole-closing-synthesized edges, see compute_atomistic_interface_mesh.cpp, don't -- they
      // aren't derived from any specific generating crystalline atom, so can't be used here, same
      // as an unresolved edge in the whole-crystal version of this algorithm).
      uint32_t max_vertex = 0;
      for(const auto& kv : mesh.edge_ideal_vector)
      {
        max_vertex = std::max( max_vertex, static_cast<uint32_t>( kv.first >> 32 ) );
        max_vertex = std::max( max_vertex, static_cast<uint32_t>( kv.first & 0xffffffffu ) );
      }
      const size_t n_verts = mesh.edge_ideal_vector.empty() ? 0 : (max_vertex + 1);

      std::vector<std::vector<uint32_t>> adj( n_verts );
      for(const auto& kv : mesh.edge_ideal_vector)
      {
        const uint32_t a = static_cast<uint32_t>( kv.first >> 32 );
        const uint32_t b = static_cast<uint32_t>( kv.first & 0xffffffffu );
        adj[a].push_back(b);
        adj[b].push_back(a);
      }

      // BFS spanning forest (one tree per connected component), propagating an accumulated
      // ideal-lattice position from an arbitrary root -- same technique as
      // compute_dxa_burgers_circuits.cpp, just over this smaller graph.
      std::vector<Vec3d> ideal_pos( n_verts, Vec3d{0.,0.,0.} );
      std::vector<uint8_t> visited( n_verts, 0 );
      std::deque<uint32_t> bfs_queue;
      for(uint32_t root=0; root<n_verts; root++)
      {
        if( visited[root] || adj[root].empty() ) { continue; }
        visited[root] = 1;
        bfs_queue.push_back(root);
        while( !bfs_queue.empty() )
        {
          const uint32_t u = bfs_queue.front(); bfs_queue.pop_front();
          for(uint32_t v : adj[u])
          {
            if( visited[v] ) { continue; }
            visited[v] = 1;
            const Vec3d& stored = mesh.edge_ideal_vector.at( InterfaceMesh::edge_key(u,v) );
            const Vec3d step = ( u < v ) ? stored : Vec3d{-stored.x,-stored.y,-stored.z};
            ideal_pos[v] = ideal_pos[u] + step;
            bfs_queue.push_back(v);
          }
        }
      }

      // every mesh edge, tree or not: compare its own direct ideal vector against the tree's
      // accumulated position difference -- a mismatch above min_burgers_norm is the fundamental
      // cycle's Burgers vector (see this file's own header comment).
      DXABurgersCircuits& result = *dxa_mesh_burgers_circuits;
      result.edges.clear();
      result.burgers_vector.clear();
      const double min_norm = *min_burgers_norm;

      for(const auto& kv : mesh.edge_ideal_vector)
      {
        const uint32_t a = static_cast<uint32_t>( kv.first >> 32 );
        const uint32_t b = static_cast<uint32_t>( kv.first & 0xffffffffu );
        const Vec3d direct = kv.second; // a->b
        const Vec3d residual = direct - ( ideal_pos[b] - ideal_pos[a] );
        if( norm(residual) <= min_norm ) { continue; }
        result.edges.push_back( { a, b } );
        result.burgers_vector.push_back( residual );
      }

      *n_mesh_core_edges = static_cast<long>( result.edges.size() );
      lout << "compute_dxa_mesh_burgers_circuits: " << result.edges.size() << " confirmed signal edges (out of "
           << mesh.edge_ideal_vector.size() << " mesh edges with an ideal vector)" << std::endl;

      {
        // histogram of |burgers_vector| in bins of 0.1 -- a real signal should cluster near known
        // crystallographic Burgers vector magnitudes (e.g. BCC's a/2<111> full dislocation is 0.866
        // in bcc_ideal_raw's a=1 units); a flat/noise-dominated distribution instead would suggest
        // min_burgers_norm needs retuning or something upstream is wrong.
        std::vector<long> hist(20,0);
        for(const auto& b : result.burgers_vector)
        {
          const double n = norm(b);
          const int bin = std::min(19, static_cast<int>(n/0.1));
          ++hist[bin];
        }
        lout << "compute_dxa_mesh_burgers_circuits DEBUG: |burgers| histogram (bin width 0.1):";
        for(int i=0;i<20;i++) { if(hist[i]>0) { lout << " [" << (i*0.1) << "-" << (i*0.1+0.1) << ":" << hist[i] << "]"; } }
        lout << std::endl;
      }
    }

    inline std::string documentation() const override final
    {
      return R"EOF(

DXA pipeline steps (vi)-(vii), mesh-restricted version: detects genuine dislocation signal via a
spanning tree + fundamental-cycle residual, computed over the atomistic interface mesh's own edge
graph (InterfaceMesh::edge_ideal_vector) rather than the whole crystal's resolved-edge graph (see
compute_dxa_burgers_circuits.cpp for that version, and this file's own header comment for why this
one is closer to OVITO's actual documented algorithm). Produces the same DXABurgersCircuits shape.

Usage example:

compute_atomistic_interface_mesh: { target_structure: BCC }
compute_dxa_mesh_burgers_circuits: { min_burgers_norm: 0.5 }

)EOF";
    }
  };

  // === register factory ===
  ONIKA_AUTORUN_INIT(compute_dxa_mesh_burgers_circuits)
  {
    OperatorNodeFactory::instance()->register_factory( "compute_dxa_mesh_burgers_circuits", make_simple_operator< ComputeDXAMeshBurgersCircuits > );
  }

}
