/*
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements. See the NOTICE file
distributed with this work for additional information
regarding copyright ownership. The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License. You may obtain a copy of the License at
  http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied. See the License for the
specific language governing permissions and limitations
under the License.
*/


#pragma once

#include <string>
#include <memory>
#include <exaStamp/operator_alias.h>
#include <exaStamp/potential_factory/pair_potential_factory.h>
#include <onika/log.h>

namespace exaStamp
{
  // Renamed pair style : the old name keeps working, with a warning, for the operators generated by the pair potential
  // template and for the potential name used in compute_force_pair_multimat.
  inline void register_deprecated_pair_style_alias( const std::string& old_name, const std::string& new_name )
  {
    for( const char* suffix : { "_compute_force" , "_compute_force_symetric" , "_multi_force" , "_plot" } )
    {
      register_deprecated_operator_alias( old_name + suffix , new_name + suffix );
    }
    auto warned = std::make_shared<bool>( false );
    PairPotentialFactory::register_factory( old_name , [old_name,new_name,warned]( YAML::Node parameters ) -> PairPotentialFactory::Instance
      {
        if( ! *warned ) { onika::lout << "Warning: pair potential '"<< old_name <<"' is deprecated, use '"<< new_name <<"' instead" << std::endl; *warned = true; }
        YAML::Node node;
        node["potential"] = new_name;
        node["parameters"] = parameters;
        return PairPotentialFactory::make_instance( node );
      } );
  }
}
